seed_everything: null
trainer:
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: /path/to/save/log/
      name: btcv
      version: vitmae_base_m0.75_btcv24
      default_hp_metric: false
  checkpoint_callback: null
  enable_checkpointing: true
  callbacks:
      - class_path: pytorch_lightning.callbacks.ModelCheckpoint
        init_args:
          filename: best
          monitor: val/l1_loss_avg
          mode: min
          # save_last: true
          save_weights_only: true
          auto_insert_metric_name: false
      - class_path: pytorch_lightning.callbacks.LearningRateMonitor
        init_args:
          logging_interval: step
      - class_path: pytorch_lightning.callbacks.RichProgressBar
  default_root_dir: /path/to/save/results/root/dir/
  gradient_clip_val: null
  gradient_clip_algorithm: null
  process_position: 0
  num_nodes: 1
  devices: -1
  accelerator: gpu
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 2
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 3000
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: null
  log_every_n_steps: 5
  strategy: ddp
  sync_batchnorm: false
  precision: 16
  enable_model_summary: true
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: true
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: false
  detect_anomaly: false
  auto_scale_batch_size: false
  prepare_data_per_node: null
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
model:
  class_path: __main__.MAEtrainer
  init_args:
    model_name: vitmae_base
    model_dict:
      pretrained: null
      in_channels: 1
      img_size: [96, 96, 96]
      patch_size: [16, 16, 16]
      hidden_size: 768
      mlp_dim: 3072
      num_layers: 12
      num_heads: 12
      pos_embed: perceptron
      dropout_rate: 0.0
      spatial_dims: 3
      masking_ratio: 0.75
      decoder_dim: 512
      decoder_heads: 8
      decoder_depth: 8
      revise_keys: []
data:
  class_path: data.btcv_dataset.BTCVDataset
  init_args:
    root_dir: /data/root/dir/
    json_path: /path/to/json/file
    cache_dir: /cache/dir/
    downsample_ratio: [1.5, 1.5, 2.0]
    batch_size: 4
    val_batch_size: 1
    num_workers: 8
    cache_num: 24
    cache_rate: 1.0
    is_ssl: true
    dist: false
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0003
    weight_decay: 0.05
lr_scheduler:
  class_path: optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
  init_args:
    warmup_epochs: 300
    max_epochs: 3000
    eta_min: 0.0001
ckpt_path: null
